package com.lexsecura.application.service;

import com.lexsecura.application.port.EmailPort;
import com.lexsecura.domain.model.Product;
import com.lexsecura.domain.model.Release;
import com.lexsecura.domain.repository.ProductRepository;
import com.lexsecura.domain.repository.ReleaseRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;

/**
 * Monitors releases approaching end-of-support (supportedUntil).
 * CRA Annexe I §2(3): Security updates must be provided for the entire support period.
 * Art. 13(8): Manufacturers shall ensure security support for at least 5 years.
 */
@Service
public class SupportEndMonitorService {

    private static final Logger log = LoggerFactory.getLogger(SupportEndMonitorService.class);

    private final ReleaseRepository releaseRepository;
    private final ProductRepository productRepository;
    private final EmailPort emailPort;
    private final WebhookService webhookService;

    @Value("${app.cra.alert-email:}")
    private String alertEmail;

    @Value("${app.support-monitor.warning-days:90}")
    private int warningDays;

    public SupportEndMonitorService(ReleaseRepository releaseRepository,
                                     ProductRepository productRepository,
                                     EmailPort emailPort,
                                     WebhookService webhookService) {
        this.releaseRepository = releaseRepository;
        this.productRepository = productRepository;
        this.emailPort = emailPort;
        this.webhookService = webhookService;
    }

    /**
     * Runs daily at 08:00 UTC to check for releases nearing end-of-support.
     */
    @Scheduled(cron = "${app.support-monitor.cron:0 0 8 * * *}")
    public void checkEndOfSupport() {
        Instant deadline = Instant.now().plus(warningDays, ChronoUnit.DAYS);
        List<Release> expiring = releaseRepository.findAllWithSupportEndingBefore(deadline);

        if (expiring.isEmpty()) {
            log.debug("No releases approaching end-of-support within {} days", warningDays);
            return;
        }

        log.warn("{} release(s) approaching end-of-support within {} days", expiring.size(), warningDays);

        for (Release release : expiring) {
            long daysLeft = ChronoUnit.DAYS.between(Instant.now(), release.getSupportedUntil());
            String severity = daysLeft <= 0 ? "EXPIRED" : daysLeft <= 30 ? "CRITICAL" : "WARNING";

            String productName = "Unknown";
            if (release.getOrgId() != null) {
                Product product = productRepository.findByIdAndOrgId(release.getProductId(), release.getOrgId()).orElse(null);
                productName = product != null ? product.getName() : "Unknown";
            }

            log.warn("[{}] Release {} v{} (product: {}) - support ends in {} days ({})",
                    severity, release.getId(), release.getVersion(), productName, daysLeft,
                    release.getSupportedUntil());

            // Send email alert
            if (alertEmail != null && !alertEmail.isBlank()) {
                String subject = String.format("[SRPDesk] %s: Release %s v%s end-of-support %s",
                        severity, productName, release.getVersion(),
                        daysLeft <= 0 ? "EXPIRED" : "in " + daysLeft + " days");
                String body = String.format("""
                        <h2>End-of-Support Alert — %s</h2>
                        <p><strong>Product:</strong> %s</p>
                        <p><strong>Release:</strong> %s</p>
                        <p><strong>Support Until:</strong> %s</p>
                        <p><strong>Days Remaining:</strong> %d</p>
                        <hr>
                        <p>Per CRA Art. 13(8), security updates must be provided for the entire support period
                        (minimum 5 years). Plan your update strategy accordingly.</p>
                        <p><small>Generated by SRPDesk — CRA Compliance Platform</small></p>
                        """, severity, productName, release.getVersion(),
                        release.getSupportedUntil(), daysLeft);

                emailPort.send(alertEmail, subject, body);
            }

            // Dispatch webhook
            if (release.getOrgId() != null) {
                webhookService.dispatch(release.getOrgId(), "SUPPORT_END_WARNING",
                        java.util.Map.of(
                                "releaseId", release.getId().toString(),
                                "productName", productName,
                                "version", release.getVersion(),
                                "supportedUntil", release.getSupportedUntil().toString(),
                                "daysLeft", String.valueOf(daysLeft),
                                "severity", severity
                        ));
            }
        }
    }
}
